"""Add habits and habit_logs tables

Revision ID: 5ae7ad6b27df
Revises: 2e39dfa19d12
Create Date: 2026-04-04 00:15:28.521244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae7ad6b27df'
down_revision = '2e39dfa19d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
