"""add_character_name_field

Revision ID: b78ba82da5c8
Revises: 86d089ac27bb
Create Date: 2026-04-04 23:19:27.183293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b78ba82da5c8'
down_revision = '86d089ac27bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battle_rewards', 'claimed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('battle_rewards_user_id_fkey', 'battle_rewards', type_='foreignkey')
    op.drop_constraint('battle_rewards_battle_id_fkey', 'battle_rewards', type_='foreignkey')
    op.create_foreign_key(None, 'battle_rewards', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'battle_rewards', 'boss_battles', ['battle_id'], ['id'])
    op.drop_constraint('uq_battle_turn', 'battle_turns', type_='unique')
    op.alter_column('boss_battles', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('boss_battles', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('boss_battles_user_id_fkey', 'boss_battles', type_='foreignkey')
    op.drop_constraint('boss_battles_boss_id_fkey', 'boss_battles', type_='foreignkey')
    op.create_foreign_key(None, 'boss_battles', 'bosses', ['boss_id'], ['id'])
    op.create_foreign_key(None, 'boss_battles', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_character_skill', 'character_skills', type_='unique')
    op.add_column('characters', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'name')
    op.create_unique_constraint('uq_character_skill', 'character_skills', ['character_id', 'skill_id'])
    op.drop_constraint(None, 'boss_battles', type_='foreignkey')
    op.drop_constraint(None, 'boss_battles', type_='foreignkey')
    op.create_foreign_key('boss_battles_boss_id_fkey', 'boss_battles', 'bosses', ['boss_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('boss_battles_user_id_fkey', 'boss_battles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('boss_battles', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('boss_battles', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_battle_turn', 'battle_turns', ['battle_id', 'turn_number', 'actor'])
    op.drop_constraint(None, 'battle_rewards', type_='foreignkey')
    op.drop_constraint(None, 'battle_rewards', type_='foreignkey')
    op.create_foreign_key('battle_rewards_battle_id_fkey', 'battle_rewards', 'boss_battles', ['battle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('battle_rewards_user_id_fkey', 'battle_rewards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('battle_rewards', 'claimed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
